# Generated by Django 3.2 on 2023-02-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0003_rename_remote_file_path_filedevice_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filedevice",
            name="host",
            field=models.CharField(default="test.com", max_length=200),
        ),
    ]
